# Based on https://github.com/t2linux/archiso-t2/blob/senpai/.github/workflows/BuildArchIso.yml

name: Build blendOS ISO
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      uses: actions/checkout@v2
    - name: Build In Docker
      if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
      run: |
        cat << EOF > entrypoint.sh
        cd /build
        useradd builduser -m
        passwd -d builduser
        pacman-key --init
        pacman-key --populate
        pacman -Syu --noconfirm --needed reflector curl
        reflector --country $(curl ipv4.myip.wtf/text/country) --sort rate -n 5 --save /etc/pacman.d/mirrorlist
        pacman -S --noconfirm --needed sudo git base-devel
        printf 'builduser ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
        chown -R builduser:builduser ./
        pacman --noconfirm --needed -S archiso git base-devel wget
        git clone https://github.com/blend-os/blend-keyring-pkg
        cd blend-keyring-pkg; makepkg --noconfirm -si
        mkarchiso -v .
        EOF

        docker run --privileged -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh
    
    - name: Upload Built ISO
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      uses: actions/upload-artifact@v2
      with:
        name: built-iso
        path: ${{ github.workspace }}/out/blendOS-*.iso
    - name: Create Tag
      id: create_tag
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      run: |
        export TAG=$(date +%Y.%m.%d.%s)
        echo "tag=${TAG}" >> $GITHUB_OUTPUT
        echo $TAG
    - name: Release
      if: ${{ github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') }}
      uses: softprops/action-gh-release@v1
      with:
         files: |
           ${{ github.workspace }}/out/blendOS-*.iso
         tag_name: ${{ steps.create_tag.outputs.tag }}
         name: blendOS-${{ steps.create_tag.outputs.tag }} - Release
         draft: ${{ contains(github.event.head_commit.message, '[draft]') }}
         prerelease: ${{ contains(github.event.head_commit.message, '[prerel]') }}
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
